version: '3.1'

services:

  mongo:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_username
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      MONGO_INITDB_DATABASE: blog_db
      MONGO_INITDB_COLLECTION: blog_collection
    ports:
      - 27017:27017
    volumes:
      - ./MongoDb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_username
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_password
      ME_CONFIG_MONGODB_URL: mongodb://mongo_username:mongo_password@mongo:27017/

  redis:
    image: redis:alpine3.18
    container_name: redis
    ports:
      - 6379:6379

  user_db:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_DB: "users_database"
      POSTGRES_USER: "user_db_username"
      POSTGRES_PASSWORD: "user_db_password"
    ports:
      - 5432:5432
  
  blog_service:
    container_name: blog_service
    build: ./BlogService
    ports:
      - 82:82
    environment:
      MongoDB__ConnectionURI: mongodb://mongo_username:mongo_password@mongo:27017/
      MongoDB__DatabaseName: blog_db
      MongoDB__CollectionName: blog_collection
      ConnectionStrings__DefaultRedisConnection: redis:6379
      ASPNETCORE_URLS: http://+:82
    depends_on:
      - mongo
      - redis

  user_service:
    container_name: user_service
    build: ./UserService
    ports:
      - 81:81
    environment:
      ConnectionStrings__DefaultSQLConnection: "Username=user_db_username;Password=user_db_password;Host=user_db;Port=5432;Database=users_database;"
      ConnectionStrings__DefaultRedisConnection: "redis:6379"
      ASPNETCORE_URLS: http://+:81
    command: sh -c "./check_user_db.sh && dotnet UserService.dll"
    depends_on:
      - redis
      - user_db

  api_gateway:
    container_name: api_gateway
    build: ./Nginx
    ports:
      - "80:80"
    depends_on:
      - user_service
      - blog_service
